---

- name: create groovy startup scripts folder
  file:
    state: directory
    path: /var/lib/jenkins/init.groovy.d
    mode: 0755
    owner: jenkins
    group: jenkins
  become: yes

- name: add basic-security.groovy
  template:
    src: basic-security.groovy
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    mode: 0644
    owner: jenkins
    group: jenkins
  become: yes

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: yes

- name: waitfor jenkins 
  uri:
    url: "{{ jenkins_url }}"
    status_code: "200,403"
  register: waitfor_jenkins
  until: waitfor_jenkins is success
  retries: 300
  delay: 1
  changed_when: false

- name: cleanup
  file:
    state: absent
    path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  become: yes

# https://github.com/geerlingguy/ansible-role-jenkins/issues/181
- name: fix a defect to disable setup wizard
  jenkins_script:
    script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
