---

- name: create .ssh
  file:
    path: ~/.ssh/
    mode: 0700
  become: yes
  become_user: jenkins

- name: scan hosts
  command: ssh-keyscan -T 30 -t rsa -p 22 "{{ item }}"
  with_items: "{{ known_hosts }}"
  register: scanned_hosts

- name: add to known_hosts
  lineinfile:
    path: ~/.ssh/known_hosts
    line: "{{ item.stdout}}"
    mode: 0640
    create: yes
  with_items: "{{ scanned_hosts.results }}"
  become: yes
  become_user: jenkins
