---

#- name: install plugins
#  command: jenkins-cli install-plugin "{{ item }}"
#  args:
#    creates: /var/lib/jenkins/plugins/{{ item }}.jpi
#  with_items: "{{ jenkins_plugins }}"

- name: install plugins
  jenkins_plugin:
    name: "{{ item }}"
    # https://github.com/ansible/ansible/issues/24864
    state: present
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    with_dependencies: yes
    # seems to be an overall timeout, not a read-timeout
    timeout: 600
    updates_expiration: 3600
  with_items: "{{ jenkins_plugins }}"
  become: yes
  register: jenkins_install_plugins

# remember: we need to restart jenkins right-away, else the plugins might potentially not be
# available via jenkins-cli prior
- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: yes
  when: jenkins_install_plugins is changed

- name: waitfor jenkins 
  uri:
    url: "{{ jenkins_url }}/cli/"
    status_code: "200,403"
  register: waitfor_jenkins
  until: waitfor_jenkins is success
  retries: 300
  delay: 1
  changed_when: false
  when: jenkins_install_plugins is changed
