---

#- name: install plugins
#  command: jenkins-cli install-plugin "{{ item }}"
#  args:
#    creates: /var/lib/jenkins/plugins/{{ item }}.jpi
#  with_items: "{{ jenkins_plugins }}"

- name: install plugins
  jenkins_plugin:
    name: "{{ item }}"
    # https://github.com/ansible/ansible/issues/24864
    state: present
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    with_dependencies: yes
    # seems to be an overall timeout, not a read-timeout
    timeout: 600
  with_items: "{{ jenkins_plugins }}"
  become: yes
  register: jenkins_install_plugins

# remember: we need to restart jenkins right-away, else the plugins might potentially not be
# available via jenkins-cli prior
- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: yes
  when: jenkins_install_plugins | changed

- name: wait_for jenkins
  shell: "curl -D - --silent --max-time 5 {{ jenkins_url }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: 60
  delay: 5
  when: jenkins_install_plugins | changed
