---

- name: restart_jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes
  become: yes

- name: restart_munin_node
  service:
    name: munin-node
    state: restarted
  become: yes
